name: NPM build

on:
    # Run this workflow from other workflows
    workflow_call:
      inputs:
        commit_id: 
          description: 'HEAD commit hash'
          required: true
          type: string
        node_version:
          default: '14.x'
          description: 'Node version'
          required: false
          type: string
        script:
          description: 'npm build script'
          required: true
          type: string
        source:
          default: 'dist'
          description: 'Source directory'
          required: false
          type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEAD_COMMIT: ${{ inputs.commit_id }}
    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Node.js build
      id: build
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node_version }}
    - run: npm ci
    - run: npm run ${{ inputs.script }}

    - name: Write commit_id.txt
      run: echo ${HEAD_COMMIT} > ./${{ inputs.source }}/commit_id.txt

    - name: Save build
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.source }}
        path: ./${{ inputs.source }}/

